### ISSUE TITLE
pkg doesn’t actually install anything

### ISSUE THREAD

**Issue by mugman174** [Generic-Linux/libtwirl#8]
Just adding this here as an issue
Also `twrl` depends on it...

**Comment by FjorgeTheHuman** [comment]
thats on you for trying to make a frontend for a wrapper thats only been in dev for like 5 hours

**Comment by mugman174** [comment]
It’s not complete yet. There’s PRs still going on.

**Comment by thewarsawpakt** [comment]
> It’s not complete yet. There’s PRs still going on.

what is it? also, I think fjorge's point is that we did put a notice on the readme

**Comment by mugman174** [comment]
Just keep this open for the project board

**Comment by FjorgeTheHuman** [comment]
fixed in PR #10
